/*
 * TencentBlueKing is pleased to support the open source community by making
 * 蓝鲸智云 - 服务治理 (BlueKing Service Governance) available.
 * Copyright (C) Tencent. All rights reserved.
 * Licensed under the MIT License (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 *  http://opensource.org/licenses/MIT
 *
 * Unless required by applicable law or agreed to in writing, software distributed under
 * the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * We undertake not to change the open source license (MIT license) applicable
 * to the current version of the project delivered to anyone in the future.
 */
/** TC-21 北极星配置类型侧边栏：业务语义步骤。 */
import { Then, When } from '../fixtures/fixtures';

When('我打开北极星新增侧边栏并选择平台自动生成', async ({ pages }) => {
  await pages.appDetailPage.polaris.openCreatePolarisAutoSideslider();
});

Then('北极星新增侧边栏应展示平台自动生成字段', async ({ pages }) => {
  await pages.appDetailPage.polaris.expectCreatePolarisAutoMode();
});

When('我提交平台自动生成北极星配置', async ({ pages }) => {
  await pages.appDetailPage.polaris.createAutoGeneratedPolarisConfig();
});

Then('平台自动生成北极星新增请求不应传递从现有引入字段', async ({ pages }) => {
  await pages.appDetailPage.polaris.expectAutoGeneratedCreateRequestParams();
});

When('我打开北极星新增侧边栏并选择从现有引入', async ({ pages }) => {
  await pages.appDetailPage.polaris.openCreatePolarisImportSideslider();
});

Then('北极星新增侧边栏应展示从现有引入字段', async ({ pages }) => {
  await pages.appDetailPage.polaris.expectCreatePolarisImportMode();
});

When('我提交从现有引入北极星配置', async ({ pages }) => {
  await pages.appDetailPage.polaris.submitImportedPolarisConfig();
});

Then('从现有引入北极星新增请求不应传递平台自动生成字段', async ({ pages }) => {
  await pages.appDetailPage.polaris.expectCreateRequestParams();
});

When('我打开首条从现有引入配置的编辑侧边栏', async ({ pages }) => {
  await pages.appDetailPage.polaris.openPrimaryImportedPolarisEditor();
});

Then('北极星编辑侧边栏应保留从现有引入并限制不可编辑字段', async ({ pages }) => {
  await pages.appDetailPage.polaris.expectPrimaryImportedPolarisEditMode();
});

When('我保存首条从现有引入配置', async ({ pages }) => {
  await pages.appDetailPage.polaris.editPrimaryPolarisConfig();
});

Then('从现有引入编辑请求不应传递平台自动生成字段', async ({ pages }) => {
  await pages.appDetailPage.polaris.expectPatchRequestParams();
});
